{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:26:14.467Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:26:14.470Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:26:14.544Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:26:14.551Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:26:14.552Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:26:24.560Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:26:24.564Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:26:34.566Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:26:34.569Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:26:44.576Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:26:44.579Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:26:54.586Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:26:54.589Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:27:04.593Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:27:04.596Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:27:14.603Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:27:14.605Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:27:24.610Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:27:24.612Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:27:34.614Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:27:34.617Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:27:44.617Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:27:44.620Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:27:54.625Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:27:54.628Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:28:04.636Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:28:04.639Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:28:14.643Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:28:14.646Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:28:24.647Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:28:24.650Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:28:34.658Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:28:34.661Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:28:44.661Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:28:44.664Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:28:54.672Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:28:54.674Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:29:04.675Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:29:04.677Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:29:14.685Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:29:14.689Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:29:24.689Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:29:24.692Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:29:34.693Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:29:34.696Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:29:44.697Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:29:45.154Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:29:45.157Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:29:45.231Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:29:45.237Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:29:45.238Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:29:55.245Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:29:55.247Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:01.974Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:01.977Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:02.051Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:02.057Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:02.057Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:02.798Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:02.801Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:02.873Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:02.879Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:02.880Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:03.835Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:03.838Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:03.912Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:03.919Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:03.920Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:04.417Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:04.419Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:04.494Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:04.501Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:04.501Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:05.114Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:05.116Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:05.188Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:05.194Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:05.195Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:05.722Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:05.724Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:05.797Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:05.803Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:05.804Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:06.331Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:06.334Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:06.408Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:06.414Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:06.415Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:07.018Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:07.020Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:07.093Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:07.099Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:07.100Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:07.604Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:07.607Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:07.678Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:07.685Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:07.685Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:08.232Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:08.234Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:08.308Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:08.314Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:08.315Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:08.750Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:08.753Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:08.823Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:08.829Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:08.830Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:18.837Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:18.839Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:28.841Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:28.843Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:38.843Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:38.846Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:48.846Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:48.848Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:49.555Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:30:49.557Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:30:49.632Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:49.639Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:30:49.639Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:30:59.643Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:30:59.646Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:31:54.938Z"}
{"level":"info","message":"Attempting to initialize user list","timestamp":"2018-05-09T22:31:54.940Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:31:55.008Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:31:55.015Z"}
{"level":"error","message":"Error Initializing User Table from DB","timestamp":"2018-05-09T22:31:55.016Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:32:05.024Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:32:05.027Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:32:15.029Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:32:15.031Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:32:25.040Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:32:25.043Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:32:35.044Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:32:35.046Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:32:45.053Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:32:45.055Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:32:55.056Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:32:55.058Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:33:05.059Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:33:05.062Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:33:15.062Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:33:15.064Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:33:25.073Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:33:25.075Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:33:35.077Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:33:35.079Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:33:45.081Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:33:45.082Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:33:55.088Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:51:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:33:55.090Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:35:06.649Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:35:06.725Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at handleConnection (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at new DB (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:20:2)\n    at Object.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/app_loader.js:19:10)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:35:06.731Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:35:16.743Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:35:16.745Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:35:26.746Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:35:26.748Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:35:36.755Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:35:36.757Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:35:46.761Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:35:46.763Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:35:56.769Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:35:56.771Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:36:06.770Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:36:06.772Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:36:16.776Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:36:16.777Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:36:26.784Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:36:26.785Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:36:36.786Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:36:36.788Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:36:46.788Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:36:46.790Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:36:56.792Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:36:56.793Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:37:06.794Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:37:06.795Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:37:16.795Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:37:16.797Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:37:26.796Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:37:26.798Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:37:36.800Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:37:36.802Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:37:46.809Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:37:46.811Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:37:56.812Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:37:56.813Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:38:06.813Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:38:06.815Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:38:16.819Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:38:16.821Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:38:26.828Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:38:26.829Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:38:36.831Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:38:36.833Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:38:46.835Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:38:46.836Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:38:56.845Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:38:56.847Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:39:06.852Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:39:06.854Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:39:16.859Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:39:16.861Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:39:26.868Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:39:26.870Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:39:36.871Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:39:36.873Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:39:46.878Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:39:46.880Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:39:56.885Z"}
{"message":"Error connecting to database: ","stack":"Error: ER_BAD_DB_ERROR: Unknown database 'invoice-tracker-db-con'\n    at Handshake.Sequence._packetToError (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Handshake.ErrorPacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)\n    at Protocol._parsePacket (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    --------------------\n    at Protocol._enqueue (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at Protocol.handshake (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)\n    at Connection.connect (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/node_modules/mysql/lib/Connection.js:130:18)\n    at Timeout.handleConnection [as _onTimeout] (/Users/shantanusaxena/Documents/invoice-tracker-mern/server/db/dbsetup.js:50:13)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'invoice-tracker-db-con'","sqlState":"42000","fatal":true,"level":"error","timestamp":"2018-05-09T22:39:56.887Z"}
{"level":"info","message":"Attempting to connect to database 127.0.0.1...","timestamp":"2018-05-09T22:39:59.974Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:40:00.056Z"}
{"level":"info","message":"Connected to database 127.0.0.1","timestamp":"2018-05-09T22:40:00.062Z"}
{"level":"info","message":"Attempting to connect to database localhost...","timestamp":"2018-05-09T22:58:06.404Z"}
{"level":"info","message":"Backend server is running on port 5000","timestamp":"2018-05-09T22:58:06.477Z"}
{"level":"info","message":"Connected to database localhost","timestamp":"2018-05-09T22:58:06.483Z"}
